# Generated by Django 5.2.5 on 2025-08-07 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciadoraDeRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da GR')),
                ('regra_validade', models.CharField(choices=[('01', 'No Embarque'), ('30', '30 Dias'), ('60', '60 Dias'), ('90', '90 Dias')], default='01', max_length=2, verbose_name='Validade do Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('modalidade', models.CharField(choices=[('FROTA', 'Frota'), ('AGREGADO', 'Agregado'), ('TERCEIRO', 'Terceiro')], default='FROTA', max_length=10, verbose_name='Modalidade')),
                ('crlv', models.FileField(blank=True, null=True, upload_to='crlv/', verbose_name='Upload CRLV')),
                ('ficha_ativacao_omnilink', models.FileField(blank=True, null=True, upload_to='fichas/', verbose_name='Ficha de Ativação Omnilink')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('gerenciadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.gerenciadoraderisco')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.veiculo')),
            ],
        ),
    ]
