# Generated by Django 5.2.5 on 2025-08-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='aprovado',
            field=models.BooleanField(default=True, verbose_name='Aprovado'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='causa_reprovacao',
            field=models.TextField(blank=True, null=True, verbose_name='Causa da Reprovação'),
        ),
    ]
